version: '3'

services:
  fastapi_test:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_test
    ports:
      - "8000:8000"
    container_name: "fastapi_test_cn"
    restart: unless-stopped