name: integration

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - "release-please--*"
  release:
    types:
      - published

jobs:
  setup:
    uses: Foxon-Consulting/github-actions/.github/workflows/setup.yml@main

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: pre-commit
        uses: Foxon-Consulting/github-actions/integration/common/pre-commit@main

  integration:
    needs:
      - setup
      - pre-commit
    uses: Foxon-Consulting/github-actions/.github/workflows/python_integration.yml@git-python-delivery
    with:
      python_version: "3.12"
      upload-artifact-name: ${{ needs.setup.outputs.name == 'fastapi_test' && needs.setup.outputs.name || null }}
      artifact-path: './dist/${{ needs.setup.outputs.name }}-${{ needs.setup.outputs.version }}-py3-none-any.whl'

  image_build:
    needs:
      - setup
      - pre-commit
      - integration
    if: ${{ needs.setup.outputs.name == 'fastapi_test' }}
    uses: Foxon-Consulting/github-actions/.github/workflows/docker_build.yml@main
    with:
      dockerfile-path: ./Dockerfile
      download-artifact-name: ${{ needs.setup.outputs.name }}
      upload-artifact-name: ${{ needs.setup.outputs.name == 'fastapi_test' && 'docker-image' || null }}

  releasing:
    runs-on: ubuntu-latest
    needs:
      - integration
    if: github.ref == 'refs/heads/main'
    steps:
      - name: releasing
        uses: Foxon-Consulting/github-actions/delivery/common/release-please@main
        with:
          RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  delivery:
      uses: Foxon-Consulting/github-actions/.github/workflows/docker_delivery.yml@main
      if: github.event_name == 'release'
      secrets: inherit
      needs:
        - setup
        - integration
        - image_build
      with:
        download-artifact-name: 'docker-image'
        deploy-image-name: ${{ needs.setup.outputs.name }}
        deploy-image-tag: ${{ needs.setup.outputs.version }}
